---
- hosts: all
  vars:
    ruby_version: '2.3.1'
    user: 'vagrant'
    home: '/home/{{ user }}'
    rbenv_root: '{{ home }}/.rbenv'
    rbenv_bash: '{{ home }}/.bash_profile'
    ror_ecom: '{{ home }}/ror_ecommerce'

  tasks:

  - name: Install the rbenv and Ruby dependencies
    apt: name={{ item }} update_cache=yes
    with_items:
       - git-core
       - curl
       - zlib1g-dev
       - build-essential
       - libssl-dev
       - libreadline-dev
       - libyaml-dev
       - libsqlite3-dev
       - sqlite3
       - libxml2-dev
       - libxslt1-dev
       - libcurl4-openssl-dev
       - python-software-properties
       - libffi-dev
    sudo: yes

### Install rbenv
  - name: Install rbenv
    git: repo=git://github.com/sstephenson/rbenv.git dest="{{ rbenv_root }}"

  - name: Install pluging rbenv
    git: repo=git://github.com/sstephenson/ruby-build.git dest="{{ rbenv_root }}/plugins/ruby-build"

  - name: Add pluging rbenv bin to PATH
    shell: echo 'export PATH="{{ rbenv_root }}/plugins/ruby-build/bin:$PATH"' >> "{{ rbenv_bash }}"

  - name: Add rbenv bin to PATH
    shell: echo 'export PATH="{{ rbenv_root }}/bin:$PATH"' >> "{{ rbenv_bash }}"

  - name: Add eval for rbenv
    shell: echo 'eval "$(rbenv init -)"' >> "{{ rbenv_bash }}"

  - name: Check rbenv instalanion
    shell: 'RBENV_ROOT={{ rbenv_root }} PATH="$RBENV_ROOT/bin:$PATH" rbenv -v'

### Install Ruby and Rails
  - name: Install Ruby with disabling the doc building step
    shell: 'RBENV_ROOT={{ rbenv_root }} PATH="$RBENV_ROOT/bin:$PATH" RUBY_CONFIGURE_OPTS=--disable-install-doc rbenv install -v {{ ruby_version }}'

  - name: Set global the new Ruby {{ ruby_version }}
    shell: 'RBENV_ROOT={{ rbenv_root }} PATH="$RBENV_ROOT/bin:$PATH" rbenv global {{ ruby_version }}'

  - name: Check ruby version
    shell: 'cat "{{ rbenv_root }}/version"'

  - name: rbenv rehash
    shell: 'RBENV_ROOT={{ rbenv_root }} PATH="$RBENV_ROOT/bin:$PATH" rbenv rehash'

  - name: 'create .gemrc'
    lineinfile: 'dest="{{ home }}/.gemrc" line="gem: --no-ri --no-rdoc" create=yes'

  - name: Install bundler
    shell: 'RBENV_ROOT={{ rbenv_root }} PATH="$RBENV_ROOT/bin:$PATH" rbenv exec gem install bundler'

  - name: Install Rails
    shell: 'RBENV_ROOT={{ rbenv_root }} PATH="$RBENV_ROOT/bin:$PATH" rbenv exec gem install rails'

  - name: Check rails version
    shell: 'RBENV_ROOT={{ rbenv_root }} PATH="$RBENV_ROOT/shims:$PATH" rails -v'

### Install Javascript Runtime
  - name: Add the Node.js PPA to apt-get
    apt_repository: repo='ppa:chris-lea/node.js' update_cache=yes
    sudo: yes

  - name: Install Javascript Runtime
    apt: name=nodejs
    sudo: yes

### Install Foreman
  - name: Install Foreman
    shell: 'RBENV_ROOT={{ rbenv_root }} PATH="$RBENV_ROOT/bin:$PATH" rbenv exec gem install foreman'

### Install ROR-ecomerce
  - name: Copy ssh-keys shl4test for bundler working throught ssh (not https)
    shell: 'cp /vagrant/ssh_keys/* "{{ home }}/.ssh"'
    sudo: yes

  - name: Make right permissions and owner/group to key file
    file: 'path={{ home }}/.ssh/shl4test owner={{ user }} group={{ user }} mode=0644'
    sudo: yes

  - name: Get github server fingerprint
    shell: 'ssh -o "StrictHostKeyChecking no" git@github.com &> /dev/null'

  - name: Install ror-ecommerce application
    git: repo=git://github.com/drhenner/ror_ecommerce.git dest="{{ ror_ecom }}"

  - name: Copy the database.yml for setup for SQLite3
    shell: 'cp config/database.yml.sqlite3 config/database.yml'
    args:
      chdir: "{{ ror_ecom }}"

  - name: Install ror-ecommerce  dependencies
    apt: name={{ item }} update_cache=yes
    with_items:
       - libmagickwand-dev
       - libpq-dev
       - libmysqlclient-dev
    sudo: yes

  - name: bundle
    shell: bundle install
    args:
      chdir: "{{ ror_ecom }}"

#  - name: file
#    shell:
#    args:
#      chdir: "{{ ror_ecom }}"

  - name: Create encryption_key file with key
    lineinfile: "dest={{ ror_ecom }}/encryption_key line='rake secret > {{ ror_ecom }}/encryption_key' create=yes"

  - name: Add encryption_key to settings playbook
    lineinfile: "dest={{ ror_ecom }}/config/settings.yml regexp='^encryption_key: ' line=encryption_key: 'grep {{ ror_ecom }}/encryption_key)'"



