---
- hosts: all
  tasks:

  - name: Install the rbenv and Ruby dependencies
    apt: name={{ item }} update_cache=yes
    with_items:
       - git-core
       - curl
       - zlib1g-dev
       - build-essential
       - libssl-dev
       - libreadline-dev
       - libyaml-dev
       - libsqlite3-dev
       - sqlite3
       - libxml2-dev
       - libxslt1-dev
       - libcurl4-openssl-dev
       - python-software-properties
       - libffi-dev
    sudo: yes

  - name: Install rbenv
    git: repo=git://github.com/sstephenson/rbenv.git dest="$HOME/.rbenv"

  - name: Install pluging rbenv
    git: repo=git://github.com/sstephenson/ruby-build.git dest="$HOME/.rbenv/plugins/ruby-build"

  - name: Copy1
    shell: echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> "$HOME/.bash_profile"

  - name: Copy2
    shell: echo 'eval "$(rbenv init -)"' >> "$HOME/.bash_profile"

  - name: Copy3
    shell: echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> "$HOME/.bash_profile"

  - name: command rbenv
    shell: source $HOME/.bash_profile
    args:
      executable: /bin/bash
